// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApTxcomS06SazKIS-i2-3coLbuDBSFbPo',
    appId: '1:28953992926:web:ef17304cd3501d53b3ac4f',
    messagingSenderId: '28953992926',
    projectId: 'teapoio-858bf',
    authDomain: 'teapoio-858bf.firebaseapp.com',
    storageBucket: 'teapoio-858bf.firebasestorage.app',
    measurementId: 'G-D5S93VF0N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcffN-eg5Jg26L9CX041UtmZYbUWUyUk',
    appId: '1:28953992926:android:aef95ff7c1ef21d8b3ac4f',
    messagingSenderId: '28953992926',
    projectId: 'teapoio-858bf',
    storageBucket: 'teapoio-858bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxv7WVaGjbVoQpr9zACDjYmvHAydOcvBw',
    appId: '1:28953992926:ios:c4e21f83346258e2b3ac4f',
    messagingSenderId: '28953992926',
    projectId: 'teapoio-858bf',
    storageBucket: 'teapoio-858bf.firebasestorage.app',
    iosBundleId: 'com.example.teapoio',
  );
}
